Repository ANSSI-FR/MLA, pull requests merged in 2025-08, with the labels that each got.

#347 Adapt fuzzer to MLA 2 API
  Cargo.lock
  Cargo.toml
  mla-fuzz-afl/Cargo.toml
  mla-fuzz-afl/src/main.rs
Labels: enhancement, refactoring

#348 Backport authenticated truncated archive reading
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/python/src/lib.rs
  doc/src/FORMAT.md
  mla-fuzz-afl/src/main.rs
  mla/benches/bench_archive.rs
  mla/src/config.rs
  mla/src/errors.rs
  mla/src/layers/encrypt.rs
  mla/src/lib.rs
  mlar/src/main.rs
  mlar/tests/integration.rs
  samples/archive_v2.mla
  samples/archive_weird.mla
Labels: enhancement

#351 Feat deny overwrite
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: enhancement

#355 Add propagation of errors in authenticated truncated reading
  mla/src/layers/encrypt.rs
Labels: enhancement

#352 Fix fuzzing MLA 2
  doc/src/FUZZING.md
  mla-fuzz-afl/src/main.rs
Labels: bug

#356 Update dependencies
  Cargo.lock
  mla/Cargo.toml
Labels: dependencies

#357 Fix benchmark when unencrypted
  bindings/C/Cargo.toml
  bindings/C/src/lib.rs
  mla/benches/bench_archive.rs
Labels: bug, tests

#358 Update CHANGELOG
  CHANGELOG.md
  bindings/C/CHANGELOG.md
  mla/CHANGELOG.md
  mlar/CHANGELOG.md
Labels: documentation

#360 Update CHANGELOG mlar
  mlar/CHANGELOG.md
Labels: documentation

#361 Doc fixes post alpha
  CHANGELOG.md
  README.md
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/python/CHANGELOG.md
  bindings/python/Cargo.toml
  bindings/python/README.md
  bindings/python/pyproject.toml
  bindings/python/src/lib.rs
  doc/src/CRYPTO.md
  doc/src/ENTRY_NAME.md
  doc/src/FORMAT.md
  doc/src/FUZZING.md
  mla/CHANGELOG.md
  mla/benches/bench_archive.rs
  mla/src/config.rs
  mla/src/crypto/hpke.rs
  mla/src/crypto/hybrid.rs
  mla/src/crypto/mlakey.rs
  mla/src/helpers.rs
  mla/src/layers/compress.rs
  mla/src/lib.rs
  mlar/mlar-upgrader/README.md
  mlar/src/main.rs
Labels: documentation

#367 Alpha fixes v2
  Cargo.lock
  README.md
  mla/src/lib.rs
  mlar/mlar-upgrader/Cargo.toml
  mlar/mlar-upgrader/src/main.rs
  mlar/mlar-upgrader/test-data/archive_v1_windows.mla
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: enhancement

#372 Fix for GFM math environment support
  .github/workflows/publish_doc.yml
  doc/src/CRYPTO.md
Labels: documentation

#374 Fix doc v2
  Cargo.lock
  README.md
Labels: documentation

#378 Add tag to mark presence of entries index
  doc/src/FORMAT.md
  mla/src/lib.rs
  samples/archive_v2.mla
  samples/archive_weird.mla
Labels: enhancement

#380 Review chord rework mlar create stdin
  README.md
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: documentation, tests

#377 Chord rework mlar create stdin
  README.md
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: bug, documentation
