Repository ANSSI-FR/MLA, pull requests merged in 2025-04, with the labels that each got.

#221 Doc crypto
  CRYPTO.md
  Cargo.lock
  Cargo.toml
  bindings/python/Cargo.lock
  bindings/python/Cargo.toml
  mla-fuzz-afl/Cargo.toml
  mla/Cargo.toml
  mla/benches/bench_archive.rs
  mla/src/config.rs
  mla/src/crypto/aesgcm.rs
  mla/src/crypto/hpke.rs
  mla/src/crypto/hybrid.rs
  mla/src/helpers.rs
  mla/src/layers/compress.rs
  mla/src/layers/encrypt.rs
  mla/src/layers/position.rs
  mla/src/layers/raw.rs
  mla/src/lib.rs
  mla/tests/aes_gcm_navs_test_vector.rs
  mlakey-parser/Cargo.toml
  mlakey-parser/src/lib.rs
  mlar/Cargo.toml
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: documentation

#267 Harden clippy
  Cargo.toml
  bindings/C/Cargo.toml
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/python/Cargo.lock
  bindings/python/Cargo.toml
  bindings/python/src/lib.rs
  curve25519-parser/Cargo.toml
  curve25519-parser/src/lib.rs
  mla-fuzz-afl/Cargo.toml
  mla-fuzz-afl/src/main.rs
  mla/Cargo.toml
  mla/benches/bench_archive.rs
  mla/src/config.rs
  mla/src/crypto/aesgcm.rs
  mla/src/crypto/ecc.rs
  mla/src/crypto/hash.rs
  mla/src/errors.rs
  mla/src/helpers.rs
  mla/src/layers/compress.rs
  mla/src/layers/encrypt.rs
  mla/src/layers/position.rs
  mla/src/layers/raw.rs
  mla/src/lib.rs
  mla/tests/aes_gcm_navs_test_vector.rs
  mlar/Cargo.toml
  mlar/src/main.rs
  mlar/tests/integration.rs
Labels: documentation, enhancement, rust

#270 bindings/c: caveat regarding thread safety added
  bindings/C/README.md
Labels: documentation, binding

#272 Doc improvements
  FORMAT.md
  README.md
  bindings/C/README.md
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/C/tests/linux-gcc-g++/info.c
  bindings/C/tests/windows-msvc/src/read.c
  bindings/python/CHANGELOG.md
  bindings/python/Cargo.toml
  bindings/python/README.md
  mla/src/helpers.rs
  mla/src/layers/compress.rs
  mla/src/lib.rs
  mlar/src/main.rs
Labels: documentation

#276 Doc fixes v2
  CRYPTO.md
Labels: documentation

#275 doc: minor fixes
  README.md
  bindings/C/README.md
  mla/src/lib.rs
Labels: documentation

#279 doc: minor fixes
  README.md
Labels: documentation

#282 Footer integrity
  CRYPTO.md
  FORMAT.md
  bindings/C/src/lib.rs
  bindings/python/Cargo.lock
  bindings/python/src/lib.rs
  mla/src/errors.rs
  mla/src/layers/encrypt.rs
Labels: rust
