Repository ANSSI-FR/MLA, pull requests merged in 2025-07, with the labels that each got.

#307 Add MLA book
  .github/workflows/publish_doc.yml
  .gitignore
  README.md
  doc/DESIGN.md
  doc/FORMAT.md
  doc/book.toml
  doc/src/CRYPTO.md
  doc/src/ENTRY_NAME.md
  doc/src/FORMAT.md
  doc/src/FUZZING.md
  doc/src/KEY_DERIVATION.md
  doc/src/KEY_FORMAT.md
  doc/src/SUMMARY.md
Labels: documentation

#298 Feature/secure permissions GitHub workflows
  .github/workflows/mla_release.yml
  .github/workflows/mlar_release.yml
  .github/workflows/test.yml
Labels: CI

#319 Review feat new format
  mla/src/entry.rs
  mla/src/layers/position.rs
  mla/src/layers/strip_head_tail.rs
  mla/src/lib.rs
Labels: documentation, enhancement

#309 Feat new format design
  Cargo.lock
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/C/tests/linux-gcc-g++/info.c
  bindings/C/tests/windows-msvc/src/read.c
  bindings/python/src/lib.rs
  doc/KEY_FORMAT.md
  doc/src/CRYPTO.md
  doc/src/ENTRY_NAME.md
  mla/Cargo.toml
  mla/src/config.rs
  mla/src/crypto/hpke.rs
  mla/src/crypto/hybrid.rs
  mla/src/entry.rs
  mla/src/errors.rs
  mla/src/format.rs
  mla/src/helpers.rs
  mla/src/info.rs
  mla/src/layers/compress.rs
  mla/src/layers/encrypt.rs
  mla/src/layers/mod.rs
  mla/src/layers/position.rs
  mla/src/layers/strip_head_tail.rs
  mla/src/lib.rs
  mlar/src/main.rs
  mlar/tests/integration.rs
  samples/archive_v2.mla
  samples/archive_weird.mla
Labels: documentation, enhancement

#330 backport C caveat regarding Send feat
  .github/workflows/publish_doc.yml
  bindings/C/README.md
Labels: binding

#334 Fix Windows and MacOS tests
  .github/workflows/py-bindings.yml
  .github/workflows/test.yml
  bindings/python/Cargo.toml
  mlar/tests/integration.rs
Labels: tests

#337 Review feat signature
  mla/src/info.rs
  mla/src/lib.rs
Labels: enhancement

#336 Add signature feature
  .github/workflows/test.yml
  Cargo.lock
  README.md
  bindings/C/README.md
  bindings/C/mla.h
  bindings/C/mla.hpp
  bindings/C/src/lib.rs
  bindings/C/tests/linux-gcc-g++/Makefile
  bindings/C/tests/linux-gcc-g++/create.c
  bindings/C/tests/linux-gcc-g++/create_interleaved.c
  bindings/C/tests/linux-gcc-g++/create_manykeys.c
  bindings/C/tests/linux-gcc-g++/create_no_early_close.c
  bindings/C/tests/linux-gcc-g++/create_set_compression_level.c
  bindings/C/tests/linux-gcc-g++/create_set_compression_level_fail_invalid.c
  bindings/C/tests/linux-gcc-g++/create_stream.c
  bindings/C/tests/linux-gcc-g++/create_unicode.c
  bindings/C/tests/linux-gcc-g++/create_write_byte_by_byte.c
  bindings/C/tests/linux-gcc-g++/info.c
  bindings/C/tests/linux-gcc-g++/open.c
  bindings/C/tests/windows-msvc/src/read.c
  bindings/C/tests/windows-msvc/src/write.c
  bindings/python/src/lib.rs
  bindings/python/tests/test_mla.py
  doc/src/CRYPTO.md
  doc/src/KEY_FORMAT.md
  mla-fuzz-afl/src/main.rs
  mla/Cargo.toml
  mla/benches/bench_archive.rs
  mla/src/config.rs
  mla/src/crypto/hash.rs
  mla/src/crypto/hybrid.rs
  mla/src/crypto/hybrid_signature.rs
  mla/src/crypto/mlakey.rs
  mla/src/crypto/mod.rs
  mla/src/entry.rs
  mla/src/errors.rs
  mla/src/helpers.rs
  mla/src/info.rs
  mla/src/layers/compress.rs
  mla/src/layers/encrypt.rs
  mla/src/layers/mod.rs
  mla/src/layers/signature.rs
  mla/src/lib.rs
  mlar/mlar-upgrader/src/main.rs
  mlar/src/main.rs
  mlar/tests/integration.rs
  samples/archive_v2.mla
  samples/archive_weird.mla
  samples/test_mlakey.mlapriv
  samples/test_mlakey.mlapub
  samples/test_mlakey_2.mlapriv
  samples/test_mlakey_2.mlapub
  samples/test_mlakey_3.mlapriv
  samples/test_mlakey_3.mlapub
  samples/test_mlakey_archive_v2.mlapub
  samples/test_mlakey_archive_v2_receiver.mlapriv
  samples/test_mlakey_archive_v2_receiver.mlapub
  samples/test_mlakey_archive_v2_sender.mlapriv
  samples/test_mlakey_archive_v2_sender.mlapub
  samples/test_mlakey_derived.mlapriv
Labels: enhancement

#339 Review better entry name
  mla/src/entry.rs
Labels: enhancement

#338 Deny more things for windows entry names interpreted as paths and relax a bit escaping
  doc/src/ENTRY_NAME.md
  mla/src/entry.rs
Labels: enhancement

#341 Review feat motw
  Cargo.lock
  mlar/Cargo.toml
  mlar/src/main.rs
Labels: enhancement

#343 Chord newtype archive entry
  bindings/python/src/lib.rs
  mla/src/entry.rs
  mla/src/format.rs
  mla/src/lib.rs
Labels: enhancement

#346 Review feat index chunk sizes
  mla/src/entry.rs
Labels: enhancement

#344 Feat index chunk sizes
  bindings/python/src/lib.rs
  doc/src/FORMAT.md
  mla/src/entry.rs
  mla/src/lib.rs
  mlar/src/main.rs
  samples/archive_v2.mla
  samples/archive_weird.mla
Labels: enhancement
